src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_commande = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_livraison = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column]
    private ?float $prix_total = null;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'commandes')]
    private Collection $livre;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $user = null;

    public function __construct()
    {
        $this->livre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prix_total;
    }

    public function setPrixTotal(float $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivre(): Collection
    {
        return $this->livre;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livre->contains($livre)) {
            $this->livre->add($livre);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livre->removeElement($livre);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CommandeType.php
<?php
namespace App\Form;
use App\Entity\Commande;
use App\Entity\User;
use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_commande')
            ->add('date_livraison')
            ->add('quantite')
            ->add('prix_total')
            ->add('livre', EntityType::class, [
                'class' => Livre::class, // Use the correct class reference
                'multiple' => true, // Other options...
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'multiple' => false,
                // ...
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php
namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/commande')]
class CommandeController extends AbstractController
{
    #[Route('/', name: 'app_commande_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livres = $commande->getLivre();

            // Persistez les livres associés à la commande
            foreach ($livres as $livre) {
                $entityManager->persist($livre);
            }

            // Persistez la commande
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, CommandeRepository $commandeRepository): Response
    {
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commandeRepository->save($commande, true);

            return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, CommandeRepository $commandeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $commandeRepository->remove($commande, true);
        }

        return $this->redirectToRoute('app_commande_index', [], Response:HTTP_SEE_OTHER);
    }}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commande_index') }}">back to list</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_commande</th>
                <th>Date_livraison</th>
                <th>Quantite</th>
                <th>Prix_total</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.dateCommande ? commande.dateCommande|date('Y-m-d') : '' }}</td>
                <td>{{ commande.dateLivraison ? commande.dateLivraison|date('Y-m-d') : '' }}</td>
                <td>{{ commande.quantite }}</td>
                <td>{{ commande.prixTotal }}</td>
                <td>
                    <a href="{{ path('app_commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_new') }}">Create new</a>
{% endblock %}

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('app_commande_index') }}">back to list</a>
{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Date_commande</th>
                <td>{{ commande.dateCommande ? commande.dateCommande|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_livraison</th>
                <td>{{ commande.dateLivraison ? commande.dateLivraison|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Quantite</th>
                <td>{{ commande.quantite }}</td>
            </tr>
            <tr>
                <th>Prix_total</th>
                <td>{{ commande.prixTotal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_index') }}">back to list</a>

    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}